export { default as Home } from './HomePage/Home'
export { default as Jot } from './Jot/Jot'
export { default as JotsContainer } from './Jot/JotsContainer'
export { default as Landing } from './LandingPage/Landing'
export { default as LogIn } from './Auth/LogIn/LogIn'
export { default as SignUp } from './Auth/SignUp/SignUp'
export { default as PrivateRoute } from './PrivateRoute/PrivateRoute'
export { default as NavBar} from './NavBar/Navbar'
export { default as SearchBar} from './SearchBar/SearchBar'