export { default as Home } from './HomePage/Home'
export { default as JotsContainer } from './Jot/JotsContainer'
export { default as Landing } from './LandingPage/Landing'
export { default as LogIn } from './LogIn/LogIn'
export { default as SignUp } from './SignUp/SignUp'
export { default as PrivateRoute } from './PrivateRoute/PrivateRoute'
export { default as NavBar} from './NavBar/Navbar'
export { default as SearchBar} from './SearchBar/SearchBar'
// export { default as AuthPage} from './Auth/AuthPage'